<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-01-17 15:48
=======
# Generated by Django 5.0.1 on 2024-01-17 15:37
>>>>>>> 56094b8343bde18c7ce3cf054d7130b5e122f350

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('ShopEzy_App', '0013_alter_customers_options'),
=======
        ('ShopEzy_App', '0013_alter_shoppingcarts_options'),
>>>>>>> 56094b8343bde18c7ce3cf054d7130b5e122f350
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcarts',
            options={'managed': False},
        ),
    ]
