# Generated by Django 5.0.1 on 2024-01-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0016_alter_cartcontainers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcarts',
            options={'managed': True},
        ),
    ]
